
name: write-sync-labels
on:
  workflow_dispatch
jobs:
  github:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run script
        run: sh ./write-labels.sh
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}